version: '3.8'

services:
  php:
    container_name: php
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
     - "81:80"
     - "443:443"
    volumes:
     - ./script/:/var/www/html
    depends_on:
     - database
     - mariadb

  database:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'MedicalChallenge'
      MYSQL_ROOT_PASSWORD: 'root'
    command: '--default-authentication-plugin=mysql_native_password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - './.mysql-data/db:/var/lib/mysql'

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: '0temp'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3307:3306'
    expose:
      - '3306'
    volumes:
      - './.mariadb-data/db:/var/lib/mysql'
